services:

  user-db:
    image: postgres:15
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - pg-user-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  map-db:
    image: postgres:15
    container_name: map-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: map_db
    ports:
      - "5434:5432"
    volumes:
      - pg-map-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tiles-nginx:
    image: nginx:latest
    container_name: tiles-nginx
    ports:
      - "8080:80"
    volumes:
      - ./tiles:/usr/share/nginx/html/tiles:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  user-service:
    build:
      context: ./user_service
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@user-db:5432/user_db
      SECRET_KEY: "supersecretkey"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 600
    ports:
      - "8001:8000"

  map-service:
    build:
      context: ./map_service
    container_name: map-service
    depends_on:
      map-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@map-db:5432/map_db
      TILES_BASE_PATH: /tiles
      SOURCE_IMAGES_PATH: /shared_uploads
      REDIS_URL: redis://redis:6379/0
      TILE_SERVICE_TASK: tile_service_app.tasks.process_task
    ports:
      - "8002:8000"
    volumes:
      - ./shared_uploads:/shared_uploads
      - ./tiles:/tiles

  tile-service:
    build: ./tile_service
    depends_on:
      - redis
    restart: always
    environment:
      REDIS_URL: redis://redis:6379/0
      SOURCE_IMAGES_PATH: /shared_uploads
      TILES_OUTPUT_PATH: /tiles
      MAP_SERVICE_URL: http://map-service:8000
    volumes:
      - ./shared_uploads:/shared_uploads
      - ./tiles:/tiles

  api-gateway:
    build:
      context: ./api_gateway
    container_name: api-gateway
    depends_on:
      - user-service
      - map-service
    environment:
      USER_SERVICE_URL: http://user-service:8000
      MAP_SERVICE_URL: http://map-service:8000
      FRONTEND_URL: http://localhost:5173
    ports:
      - "8000:8000"

volumes:
  pg-user-data:
  pg-map-data: